# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'template.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpinBox, QWidget)

from custom_widgets import SignalPlotter

class Ui_Bioscope(object):
    def setupUi(self, Bioscope):
        if not Bioscope.objectName():
            Bioscope.setObjectName(u"Bioscope")
        Bioscope.resize(1002, 650)
        self.actionSave = QAction(Bioscope)
        self.actionSave.setObjectName(u"actionSave")
        self.action_png = QAction(Bioscope)
        self.action_png.setObjectName(u"action_png")
        self.centralwidget = QWidget(Bioscope)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = SignalPlotter(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 100, 811, 521))
        self.FrameControl = QFrame(self.centralwidget)
        self.FrameControl.setObjectName(u"FrameControl")
        self.FrameControl.setGeometry(QRect(0, 0, 1001, 91))
        self.FrameControl.setStyleSheet(u"")
        self.FrameControl.setFrameShape(QFrame.Shape.StyledPanel)
        self.FrameControl.setFrameShadow(QFrame.Shadow.Raised)
        self.buttonSingle = QPushButton(self.FrameControl)
        self.buttonSingle.setObjectName(u"buttonSingle")
        self.buttonSingle.setGeometry(QRect(120, 10, 101, 71))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.buttonSingle.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackPause))
        self.buttonSingle.setIcon(icon)
        self.buttonSingle.setIconSize(QSize(25, 25))
        self.runStopButton = QPushButton(self.FrameControl)
        self.runStopButton.setObjectName(u"runStopButton")
        self.runStopButton.setGeometry(QRect(10, 10, 101, 71))
        self.runStopButton.setFont(font)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.runStopButton.setIcon(icon1)
        self.runStopButton.setIconSize(QSize(25, 25))
        self.labelMode = QLabel(self.FrameControl)
        self.labelMode.setObjectName(u"labelMode")
        self.labelMode.setGeometry(QRect(250, 10, 51, 21))
        font1 = QFont()
        font1.setPointSize(12)
        self.labelMode.setFont(font1)
        self.comboBox = QComboBox(self.FrameControl)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(310, 10, 91, 26))
        self.buttonAutoscale = QPushButton(self.FrameControl)
        self.buttonAutoscale.setObjectName(u"buttonAutoscale")
        self.buttonAutoscale.setGeometry(QRect(250, 40, 151, 31))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomFitBest))
        self.buttonAutoscale.setIcon(icon2)
        self.frameCH1 = QFrame(self.centralwidget)
        self.frameCH1.setObjectName(u"frameCH1")
        self.frameCH1.setGeometry(QRect(820, 110, 171, 121))
        self.frameCH1.setStyleSheet(u"border-color: rgb(129, 61, 156);")
        self.frameCH1.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCH1.setFrameShadow(QFrame.Shadow.Raised)
        self.checkCH1 = QCheckBox(self.frameCH1)
        self.checkCH1.setObjectName(u"checkCH1")
        self.checkCH1.setGeometry(QRect(40, 10, 91, 24))
        self.labelCH1off = QLabel(self.frameCH1)
        self.labelCH1off.setObjectName(u"labelCH1off")
        self.labelCH1off.setGeometry(QRect(10, 47, 66, 21))
        self.label = QLabel(self.frameCH1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 80, 66, 21))
        self.spinCH1offset = QSpinBox(self.frameCH1)
        self.spinCH1offset.setObjectName(u"spinCH1offset")
        self.spinCH1offset.setGeometry(QRect(80, 40, 71, 27))
        self.spinCH1offset.setSingleStep(5)
        self.spinCH1scale = QSpinBox(self.frameCH1)
        self.spinCH1scale.setObjectName(u"spinCH1scale")
        self.spinCH1scale.setGeometry(QRect(80, 80, 71, 27))
        self.frameCH2 = QFrame(self.centralwidget)
        self.frameCH2.setObjectName(u"frameCH2")
        self.frameCH2.setGeometry(QRect(820, 240, 171, 121))
        self.frameCH2.setStyleSheet(u"border-color: rgb(129, 61, 156);")
        self.frameCH2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCH2.setFrameShadow(QFrame.Shadow.Raised)
        self.checkCH1_2 = QCheckBox(self.frameCH2)
        self.checkCH1_2.setObjectName(u"checkCH1_2")
        self.checkCH1_2.setGeometry(QRect(40, 10, 91, 24))
        self.labelCH1off_2 = QLabel(self.frameCH2)
        self.labelCH1off_2.setObjectName(u"labelCH1off_2")
        self.labelCH1off_2.setGeometry(QRect(10, 47, 66, 21))
        self.label_2 = QLabel(self.frameCH2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 66, 21))
        self.spinCH1offset_2 = QSpinBox(self.frameCH2)
        self.spinCH1offset_2.setObjectName(u"spinCH1offset_2")
        self.spinCH1offset_2.setGeometry(QRect(80, 40, 71, 27))
        self.spinCH1offset_2.setSingleStep(5)
        self.spinCH1scale_2 = QSpinBox(self.frameCH2)
        self.spinCH1scale_2.setObjectName(u"spinCH1scale_2")
        self.spinCH1scale_2.setGeometry(QRect(80, 80, 71, 27))
        self.frameCH1_3 = QFrame(self.centralwidget)
        self.frameCH1_3.setObjectName(u"frameCH1_3")
        self.frameCH1_3.setGeometry(QRect(820, 370, 171, 121))
        self.frameCH1_3.setStyleSheet(u"border-color: rgb(129, 61, 156);")
        self.frameCH1_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCH1_3.setFrameShadow(QFrame.Shadow.Raised)
        self.checkCH1_3 = QCheckBox(self.frameCH1_3)
        self.checkCH1_3.setObjectName(u"checkCH1_3")
        self.checkCH1_3.setGeometry(QRect(40, 10, 91, 24))
        self.labelCH1off_3 = QLabel(self.frameCH1_3)
        self.labelCH1off_3.setObjectName(u"labelCH1off_3")
        self.labelCH1off_3.setGeometry(QRect(10, 47, 66, 21))
        self.label_3 = QLabel(self.frameCH1_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 80, 66, 21))
        self.spinCH1offset_3 = QSpinBox(self.frameCH1_3)
        self.spinCH1offset_3.setObjectName(u"spinCH1offset_3")
        self.spinCH1offset_3.setGeometry(QRect(80, 40, 71, 27))
        self.spinCH1offset_3.setSingleStep(5)
        self.spinCH1scale_3 = QSpinBox(self.frameCH1_3)
        self.spinCH1scale_3.setObjectName(u"spinCH1scale_3")
        self.spinCH1scale_3.setGeometry(QRect(80, 80, 71, 27))
        self.frameCH1_4 = QFrame(self.centralwidget)
        self.frameCH1_4.setObjectName(u"frameCH1_4")
        self.frameCH1_4.setGeometry(QRect(820, 500, 171, 121))
        self.frameCH1_4.setStyleSheet(u"border-color: rgb(129, 61, 156);")
        self.frameCH1_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCH1_4.setFrameShadow(QFrame.Shadow.Raised)
        self.checkCH1_4 = QCheckBox(self.frameCH1_4)
        self.checkCH1_4.setObjectName(u"checkCH1_4")
        self.checkCH1_4.setGeometry(QRect(40, 10, 91, 24))
        self.labelCH1off_4 = QLabel(self.frameCH1_4)
        self.labelCH1off_4.setObjectName(u"labelCH1off_4")
        self.labelCH1off_4.setGeometry(QRect(10, 47, 66, 21))
        self.label_4 = QLabel(self.frameCH1_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 80, 66, 21))
        self.spinCH1offset_4 = QSpinBox(self.frameCH1_4)
        self.spinCH1offset_4.setObjectName(u"spinCH1offset_4")
        self.spinCH1offset_4.setGeometry(QRect(80, 40, 71, 27))
        self.spinCH1offset_4.setSingleStep(5)
        self.spinCH1scale_4 = QSpinBox(self.frameCH1_4)
        self.spinCH1scale_4.setObjectName(u"spinCH1scale_4")
        self.spinCH1scale_4.setGeometry(QRect(80, 80, 71, 27))
        Bioscope.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(Bioscope)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1002, 23))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSave_as = QMenu(self.menuFile)
        self.menuSave_as.setObjectName(u"menuSave_as")
        Bioscope.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuSave_as.menuAction())
        self.menuSave_as.addAction(self.action_png)

        self.retranslateUi(Bioscope)

        QMetaObject.connectSlotsByName(Bioscope)
    # setupUi

    def retranslateUi(self, Bioscope):
        Bioscope.setWindowTitle(QCoreApplication.translate("Bioscope", u"Bioscope", None))
        self.actionSave.setText(QCoreApplication.translate("Bioscope", u"Save", None))
        self.action_png.setText(QCoreApplication.translate("Bioscope", u".png", None))
        self.buttonSingle.setText(QCoreApplication.translate("Bioscope", u"Single", None))
        self.runStopButton.setText(QCoreApplication.translate("Bioscope", u"Run", None))
        self.labelMode.setText(QCoreApplication.translate("Bioscope", u"Mode:", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Bioscope", u"Trigger", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Bioscope", u"Roll", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Bioscope", u"XY", None))

        self.buttonAutoscale.setText(QCoreApplication.translate("Bioscope", u"Autoscale", None))
        self.checkCH1.setText(QCoreApplication.translate("Bioscope", u"Channel 1", None))
        self.labelCH1off.setText(QCoreApplication.translate("Bioscope", u"Offset:", None))
        self.label.setText(QCoreApplication.translate("Bioscope", u"Scale:", None))
        self.spinCH1offset.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV", None))
        self.spinCH1scale.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV/div", None))
        self.checkCH1_2.setText(QCoreApplication.translate("Bioscope", u"Channel 2", None))
        self.labelCH1off_2.setText(QCoreApplication.translate("Bioscope", u"Offset:", None))
        self.label_2.setText(QCoreApplication.translate("Bioscope", u"Scale:", None))
        self.spinCH1offset_2.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV", None))
        self.spinCH1scale_2.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV/div", None))
        self.checkCH1_3.setText(QCoreApplication.translate("Bioscope", u"Channel 3", None))
        self.labelCH1off_3.setText(QCoreApplication.translate("Bioscope", u"Offset:", None))
        self.label_3.setText(QCoreApplication.translate("Bioscope", u"Scale:", None))
        self.spinCH1offset_3.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV", None))
        self.spinCH1scale_3.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV/div", None))
        self.checkCH1_4.setText(QCoreApplication.translate("Bioscope", u"Channel 3", None))
        self.labelCH1off_4.setText(QCoreApplication.translate("Bioscope", u"Offset:", None))
        self.label_4.setText(QCoreApplication.translate("Bioscope", u"Scale:", None))
        self.spinCH1offset_4.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV", None))
        self.spinCH1scale_4.setSpecialValueText(QCoreApplication.translate("Bioscope", u"mV/div", None))
        self.menuFile.setTitle(QCoreApplication.translate("Bioscope", u"File", None))
        self.menuSave_as.setTitle(QCoreApplication.translate("Bioscope", u"Save as", None))
    # retranslateUi

